### ISSUE TITLE
Problems when opening brackets within LISPs

### ISSUE THREAD

**Issue by mauricioszabo** [parinfer/parinfer.js#114] opened 2016-05-23 21:18 UTC
In the following code:

``` clojure
(defn foo []
  (str 1 (+ 2 3) 5))
```

If I add a `{` right after the `+`:

``` clojure
(defn foo []
  (str 1 (+ {2 3) 5))
```

It changes the inner parenthesis to close after `5`:

``` clojure
(defn foo []
  (+ 1 (+ {2 3 5})))
```

I believe the right way is not change the already balanced code:

``` clojure
(defn foo []
  (str 1 (+ {2 3}) 5))
```

tldr; I _think_ I already reported this issue, but I wasn't able to find it...

**Comment by shaunlebron** [comment] 2016-06-01 11:00
Thanks for reporting.  Duplicate of https://github.com/shaunlebron/parinfer/issues/102

**Closed as completed by shaunlebron** 2016-06-01 11:00 UTC
